name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git clone --depth 1 https://github.com/jault-figure/cpr-target
      - run: date > cpr-target/date.txt
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          path: cpr-target
          commit-message: Deploy from cpr-demo
          branch: special-feature-update
          base: main
          delete-branch: true
          title: Deploy from cpr-demo
          body: |
            This is an automated pull request from cpr-demo
